[package]
name = "overload"
version = "0.2.0"
edition = "2021"

[dependencies]
tokio = { version = "1.42.0", features = ["full"] }
rand = "0.9.0-beta.1"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true
